import = ["/home/kambiz/.config/alacritty/themes/blood_moon.toml"]

[env]
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 20.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[window]
opacity = 0.9
